[package]
name = "asocks5"
version = "0.1.0"
authors = ["mut"]
edition = "2018"

[dependencies]
byteorder = "1.2.3"
bytes = "^0.4"
failure = "0.1.1"
futures = "0.1.23"
log = "^0.4"
net2 = "^0.2"
tokio = { version="^0.1.7", features = ["async-await-preview"] }
tokio-async-await = "0.1.0"
tokio-io = "^0.1"

[dev-dependencies]
structopt = "*"
trust-dns-resolver = "*"
